### PR TITLE
Won't scroll and block is misisng because of position fixed

### PR DESCRIPTION
**Pull request by Matthewbgithub**

### CODE REVIEW

**Comment by bluey31** [comment]
Is Home page meant to be empty so far?

**Comment by bluey31** [comment]
Check GCSE Courses page - Is it meant to be like that?

**Comment by Matthewbgithub** [comment]
oh lol whoops no, and yeh i thought sumedhw as doing homepage but i can make one anyway

**Comment by bluey31** [comment]
Keep homepage empty for now.

**Comment by Matthewbgithub** [comment]
okay bb

**Comment by bluey31** [comment]
Code is really nice and clean - Good Job ;)

**Comment by Matthewbgithub** [comment]
yas

**Comment by bluey31** [comment]
Looks good - merging now

**Pull request merged**
